[package]
name = "reverse_endian_test_suite"
version = "0.0.0"
authors = ["Michael Yang <mikkyangg@gmail.com>"]
edition = "2018"
publish = false

[dependencies.reverse_endian]
path = "../reverse_endian"
features = ["derive"]
